### ISSUE TITLE
Laravel 9 Composer Problem

### ISSUE THREAD

**Issue by aliosmanyuksel** [cuneytyuksel/turkey-cities#2]
Merhaba,

Laravel 9 ile kullanımda sorun yaşıyorum.

❯ composer require cuneytyuksel/turkey-cities
Info from https://repo.packagist.org: #StandWithUkrainerequire cuneytyuksel/turkey-cities                                                                                       ░▒▓ ✔  05:54:53  
Using version ^1.0 for cuneytyuksel/turkey-cities
./composer.json has been updated
Running composer update cuneytyuksel/turkey-cities
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cuneytyuksel/turkey-cities[1.0.5, ..., 1.0.6] require maatwebsite/excel ~3.1.14 -> satisfiable by maatwebsite/excel[3.1.14, ..., 3.1.x-dev].
    - cuneytyuksel/turkey-cities[1.0, ..., 1.0.4] require maatwebsite/excel ~2.1.0 -> satisfiable by maatwebsite/excel[v2.1.0, ..., 2.1.x-dev].
    - maatwebsite/excel[3.1.36, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.24.1].
    - maatwebsite/excel[v2.1.0, ..., v2.1.3] require illuminate/cache 5.0.*|5.1.*|5.2.* -> found illuminate/cache[v5.0.0, ..., 5.2.x-dev] but these were not loaded, likely because it conflicts with another require.
    - maatwebsite/excel[2.1.4, ..., 2.1.9] require illuminate/cache 5.0.*|5.1.*|5.2.*|5.3.* -> found illuminate/cache[v5.0.0, ..., 5.3.x-dev] but these were not loaded, likely because it conflicts with another require.
    - maatwebsite/excel[2.1.10, ..., 2.1.20] require illuminate/cache 5.0.*|5.1.*|5.2.*|5.3.*|5.4.* -> found illuminate/cache[v5.0.0, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - maatwebsite/excel[2.1.21, ..., 2.1.24] require illuminate/cache 5.0.*|5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> found illuminate/cache[v5.0.0, ..., 5.5.x-dev] but these were not loaded, likely because it conflicts with another require.
    - maatwebsite/excel[2.1.25, ..., 2.1.29] require illuminate/cache 5.0.*|5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.* -> found illuminate/cache[v5.0.0, ..., 5.6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - maatwebsite/excel[2.1.30, ..., 2.1.x-dev] require illuminate/cache ^5.0 -> found illuminate/cache[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phpoffice/phpspreadsheet[1.23.0, ..., 1.24.1] require psr/simple-cache ^1.0 || ^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - maatwebsite/excel[3.1.14, ..., 3.1.25] require php ^7.0 -> your php version (8.1.9) does not satisfy that requirement.
    - maatwebsite/excel[3.1.26, ..., 3.1.35] require illuminate/support 5.8.*|^6.0|^7.0|^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires cuneytyuksel/turkey-cities ^1.0 -> satisfiable by cuneytyuksel/turkey-cities[1.0, ..., 1.0.6].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require cuneytyuksel/turkey-cities:*" to figure out if any version is installable, or "composer require cuneytyuksel/turkey-cities:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by cuneytyuksel** [comment]
Merhaba @aliosmanyuksel ,
Laravel 9 için paketi güncelledim.

**Comment by aliosmanyuksel** [comment]
Teşekkürler 😇 @cuneytyuksel
